/**
 * Matrix sections 20 and 21 - the API contract.
 *
 * Two separate claims are under test here:
 *
 *   20.x  The committed snapshot `packages/api-types/src/generated.ts` still
 *         describes the live Django-Ninja schema. The snapshot is committed so
 *         that `npm run build` works with the API switched off, and that same
 *         convenience is what lets it drift silently.
 *
 *   21.x  No API shape is ever hand-written in `apps/web`, and the generated
 *         types actually bite - a misspelled field or a wrong primitive has to
 *         fail `tsc`, not merely look tidy.
 *
 * The 20.x rows need a running API. They SKIP (never fail) when it is
 * unreachable, because offline builds are a supported mode. They must not skip
 * when it is reachable, so reachability is probed here rather than inferred
 * from the script's exit code alone.
 */
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { afterAll, beforeAll, describe, expect, it } from "vitest";
import ts from "typescript";

const require = createRequire(import.meta.url);

const WEB_ROOT = fileURLToPath(new URL("../", import.meta.url));
const REPO_ROOT = path.resolve(WEB_ROOT, "..", "..");
const DRIFT_SCRIPT = path.join(REPO_ROOT, "scripts", "check-api-types-drift.mjs");
const SNAPSHOT = path.join(REPO_ROOT, "packages", "api-types", "src", "generated.ts");
const API_TYPES_ENTRY = "packages/api-types/src/index.ts";
const SCHEMA_URL =
  process.env.API_TYPES_SCHEMA_URL ?? "http://localhost:8000/api/openapi.json";

const EXIT_DRIFT = 1;
const EXIT_API_UNREACHABLE = 2;

/** Forward slashes only: these end up inside a generated tsconfig JSON. */
function posix(p: string): string {
  return p.split("\\").join("/");
}

function runDriftScript(extraArgs: string[] = [], env: Record<string, string> = {}) {
  const result = spawnSync(process.execPath, [DRIFT_SCRIPT, ...extraArgs], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    env: { ...process.env, ...env },
    timeout: 120_000,
  });
  return {
    status: result.status ?? -1,
    output: `${result.stdout ?? ""}${result.stderr ?? ""}`,
  };
}

let apiReachable = false;

beforeAll(async () => {
  try {
    const response = await fetch(SCHEMA_URL, { signal: AbortSignal.timeout(5_000) });
    apiReachable = response.ok;
  } catch {
    apiReachable = false;
  }
});

describe("20. generated types match the live OpenAPI schema", () => {
  it("the drift script exists and is executable by node", () => {
    const source = readFileSync(DRIFT_SCRIPT, "utf8");
    expect(source).toContain("openapi-typescript");
    expect(source).toContain("npm run generate:types");
  });

  it("the committed snapshot is a generated file, not hand-edited", () => {
    const snapshot = readFileSync(SNAPSHOT, "utf8");
    expect(snapshot).toContain("auto-generated by openapi-typescript");
    expect(snapshot).toContain("Do not make direct changes to the file");
    expect(snapshot.length).toBeGreaterThan(1_000);
  });

  it(
    "20.1 the committed snapshot matches the live schema",
    { timeout: 120_000 },
    (context) => {
      if (!apiReachable) {
        // Skipped, not passed: the offline case is exactly why the snapshot is
        // committed. It must still run whenever the API is up.
        context.skip(`API unreachable at ${SCHEMA_URL}`);
        return;
      }

      const { status, output } = runDriftScript();
      expect(status, output).not.toBe(EXIT_API_UNREACHABLE);
      expect(status, output).not.toBe(EXIT_DRIFT);
      expect(status, output).toBe(0);
      expect(output).toContain("in sync");
    },
  );

  it(
    "20.2 a drifted snapshot fails and names the fix command",
    { timeout: 120_000 },
    (context) => {
      if (!apiReachable) {
        context.skip(`API unreachable at ${SCHEMA_URL}`);
        return;
      }

      // Point the script at a deliberately corrupted copy of the snapshot. The
      // real committed file is never touched.
      const dir = mkdtempSync(path.join(tmpdir(), "ccc-drift-"));
      try {
        const drifted = path.join(dir, "drifted.ts");
        writeFileSync(
          drifted,
          readFileSync(SNAPSHOT, "utf8").replace("HealthOut:", "HealthOutRenamed:"),
          "utf8",
        );

        const { status, output } = runDriftScript([], { API_TYPES_SNAPSHOT: drifted });

        expect(status, output).toBe(EXIT_DRIFT);
        expect(output).toContain("DRIFT");
        expect(output).toContain("npm run generate:types");
        // The message has to point at the actual difference, not just complain.
        expect(output).toContain("HealthOut");
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    },
  );

  it(
    "20.3 generation is deterministic - two runs produce identical bytes",
    { timeout: 180_000 },
    (context) => {
      if (!apiReachable) {
        context.skip(`API unreachable at ${SCHEMA_URL}`);
        return;
      }

      const dir = mkdtempSync(path.join(tmpdir(), "ccc-determinism-"));
      try {
        const first = path.join(dir, "first.ts");
        const second = path.join(dir, "second.ts");

        expect(runDriftScript(["--emit", first]).status).toBe(0);
        expect(runDriftScript(["--emit", second]).status).toBe(0);

        const a = readFileSync(first, "utf8");
        const b = readFileSync(second, "utf8");
        expect(a.length).toBeGreaterThan(1_000);
        expect(a).toBe(b);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    },
  );

  it("the script skips gracefully, and says so, when the API is unreachable", () => {
    // Port 1 is reserved and never listening, so this is a stable "API down".
    const { status, output } = runDriftScript([], {
      API_TYPES_SCHEMA_URL: "http://127.0.0.1:1/api/openapi.json",
    });

    expect(status).toBe(EXIT_API_UNREACHABLE);
    expect(status).not.toBe(EXIT_DRIFT);
    expect(output).toContain("SKIPPED");
    expect(output).toContain("offline");
  });
});

// ---------------------------------------------------------------------------
// 21.1 - no hand-written API types
// ---------------------------------------------------------------------------

/** Names shaped like an API payload. Django-Ninja schemas are `*Out` / `*In`. */
const API_TYPE_NAME = /(Out|In|Dto|DTO|Payload|ApiResponse)$/;

/** A declaration is legitimate when it is derived from the generated package. */
const DERIVED_FROM_GENERATED = /\b(Schema|ApiSchemas|ApiOperations|ApiPaths|OperationResponse|OperationRequestBody|components|operations|paths)\b/;

function listTypeScriptFiles(root: string): string[] {
  const out: string[] = [];
  const skip = new Set(["node_modules", ".next", ".turbo", "test-results", "playwright-report"]);
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (skip.has(entry.name)) continue;
      const full = `${dir}/${entry.name}`;
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) out.push(full);
    }
  };
  walk(root);
  return out;
}

interface Declaration {
  file: string;
  name: string;
  derived: boolean;
}

function apiShapedDeclarations(file: string, source: string): Declaration[] {
  const sourceFile = ts.createSourceFile(
    file,
    source,
    ts.ScriptTarget.Latest,
    true,
    file.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  const found: Declaration[] = [];

  const visit = (node: ts.Node): void => {
    if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
      const name = node.name.text;
      if (API_TYPE_NAME.test(name)) {
        const body = ts.isTypeAliasDeclaration(node)
          ? node.type.getText(sourceFile)
          : node.members.map((member) => member.getText(sourceFile)).join("\n");
        found.push({ file, name, derived: DERIVED_FROM_GENERATED.test(body) });
      }
    }
    node.forEachChild(visit);
  };

  visit(sourceFile);
  return found;
}

describe("21.1 zero hand-written API types in apps/web", () => {
  const files = listTypeScriptFiles(WEB_ROOT.replace(/[\\/]$/, ""));

  it("scans the real source tree", () => {
    expect(files.length).toBeGreaterThan(15);
    expect(files.some((file) => file.endsWith("lib/api/client.ts"))).toBe(true);
  });

  it("declares no API-shaped type that is not derived from @ccc/api-types", () => {
    const handWritten = files
      .flatMap((file) => apiShapedDeclarations(file, readFileSync(file, "utf8")))
      .filter((declaration) => !declaration.derived)
      .map(
        (declaration) =>
          `${posix(declaration.file.slice(WEB_ROOT.length))}: ${declaration.name}`,
      );

    expect(handWritten).toEqual([]);
  });

  it("actually imports the generated package where API shapes are needed", () => {
    const importers = files.filter((file) =>
      readFileSync(file, "utf8").includes("@ccc/api-types"),
    );
    expect(importers.length).toBeGreaterThan(2);
  });

  it("the generated package re-exports only from the generated module", () => {
    const index = readFileSync(path.join(REPO_ROOT, API_TYPES_ENTRY), "utf8");
    // Every type in the public surface has to trace back to ./generated.
    expect(index).toContain('from "./generated"');
    const declarations = apiShapedDeclarations(API_TYPES_ENTRY, index).filter(
      (declaration) => !declaration.derived,
    );
    expect(declarations.map((declaration) => declaration.name)).toEqual([]);
  });

  it("the detector would catch a hand-written API type", () => {
    const probe = apiShapedDeclarations(
      "probe.ts",
      "export interface EpisodeBriefOut { youtube_id: string; title: string }",
    );
    expect(probe).toHaveLength(1);
    expect(probe[0].derived).toBe(false);
  });

  it("the detector accepts a type derived from the generated schema", () => {
    const probe = apiShapedDeclarations(
      "probe.ts",
      'import type { Schema } from "@ccc/api-types";\nexport type EpisodeOut = Schema<"EpisodeOut">;',
    );
    expect(probe).toHaveLength(1);
    expect(probe[0].derived).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// 21.2 - the generated types actually bite (compile-time probe)
// ---------------------------------------------------------------------------

/**
 * Each probe is compiled in a throwaway directory OUTSIDE the repo, through its
 * own tsconfig. Deliberately-broken code must never live anywhere that
 * `npm run typecheck` can see, or this test would break the repo's own gate.
 */
let probeDir = "";

beforeAll(() => {
  probeDir = mkdtempSync(path.join(tmpdir(), "ccc-type-probe-"));
});

afterAll(() => {
  if (probeDir) rmSync(probeDir, { recursive: true, force: true });
});

interface TscResult {
  status: number;
  output: string;
}

function typecheckProbe(name: string, source: string): TscResult {
  const file = path.join(probeDir, `${name}.ts`);
  const configPath = path.join(probeDir, `tsconfig.${name}.json`);

  writeFileSync(file, source, "utf8");
  writeFileSync(
    configPath,
    JSON.stringify(
      {
        compilerOptions: {
          strict: true,
          noEmit: true,
          target: "ES2017",
          module: "esnext",
          moduleResolution: "bundler",
          skipLibCheck: true,
          lib: ["esnext", "dom"],
          types: [],
          baseUrl: posix(REPO_ROOT),
          paths: { "@ccc/api-types": [API_TYPES_ENTRY] },
        },
        files: [posix(file)],
      },
      null,
      2,
    ),
    "utf8",
  );

  const tsc = require.resolve("typescript/bin/tsc");
  const result = spawnSync(process.execPath, [tsc, "--project", configPath], {
    encoding: "utf8",
    timeout: 120_000,
  });

  return {
    status: result.status ?? -1,
    output: `${result.stdout ?? ""}${result.stderr ?? ""}`,
  };
}

const VALID_HEALTH = `
import type { Schema, OperationResponse } from "@ccc/api-types";

const health: Schema<"HealthOut"> = {
  status: "ok",
  database: { ok: true, detail: "select 1" },
  redis: { ok: true, detail: "PONG" },
};

const fromOperation: OperationResponse<"config_api_health"> = health;

export { health, fromOperation };
`;

describe("21.2 the generated types actually bite", () => {
  it(
    "control: correct usage compiles cleanly, so a failure below means something",
    { timeout: 120_000 },
    () => {
      const result = typecheckProbe("control", VALID_HEALTH);
      expect(result.status, result.output).toBe(0);
      expect(result.output.trim()).toBe("");
    },
  );

  it("rejects a misspelled field name", { timeout: 120_000 }, () => {
    const result = typecheckProbe(
      "misspelled",
      `
import type { Schema } from "@ccc/api-types";

export const health: Schema<"HealthOut"> = {
  statuss: "ok",
  database: { ok: true, detail: "" },
  redis: { ok: true, detail: "" },
};
`,
    );
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/statuss/);
  });

  it("rejects a wrong primitive type", { timeout: 120_000 }, () => {
    const result = typecheckProbe(
      "wrong-primitive",
      `
import type { Schema } from "@ccc/api-types";

export const health: Schema<"HealthOut"> = {
  status: 200,
  database: { ok: "yes", detail: "" },
  redis: { ok: true, detail: "" },
};
`,
    );
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/not assignable to type 'string'/);
  });

  it("rejects an unknown schema name", { timeout: 120_000 }, () => {
    const result = typecheckProbe(
      "unknown-schema",
      `
import type { Schema } from "@ccc/api-types";

export type Nope = Schema<"ThisSchemaDoesNotExistOut">;
`,
    );
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/ThisSchemaDoesNotExistOut/);
  });

  it("rejects an unknown operationId", { timeout: 120_000 }, () => {
    const result = typecheckProbe(
      "unknown-operation",
      `
import type { OperationResponse } from "@ccc/api-types";

export type Nope = OperationResponse<"there_is_no_such_operation">;
`,
    );
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/there_is_no_such_operation/);
  });

  it("rejects a missing required field", { timeout: 120_000 }, () => {
    const result = typecheckProbe(
      "missing-field",
      `
import type { Schema } from "@ccc/api-types";

export const health: Schema<"HealthOut"> = {
  status: "ok",
  database: { ok: true, detail: "" },
};
`,
    );
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/redis/);
  });
});
