/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus dependency reachability. Never authenticated.
         */
        get: operations["config_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["podcast_api_public_list_channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{slug}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Channel Grid
         * @description 🎬 IMDb-style season grid. One calendar year = one season.
         *
         *     Columns are years, rows are the episode's position within that year. Reading
         *     down a column walks the year in order; reading across compares the same point
         *     across years.
         */
        get: operations["podcast_api_public_get_channel_grid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["podcast_api_public_get_channel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Episodes */
        get: operations["podcast_api_public_list_episodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Episode */
        get: operations["podcast_api_public_get_episode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["podcast_api_public_list_topics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Topics
         * @description Existing topics matching a partial input, most-used first.
         *
         *     🚨 This is the main defence against topic sprawl: if users pick an existing
         *     label, "find every episode about X" keeps working.
         *
         *     ⚠️ MUST be declared BEFORE /topics/{slug}. Routes match in declaration order, so
         *     with {slug} first this path resolves as slug="suggest" and 404s. That exact bug
         *     was live on 2026-08-08.
         */
        get: operations["podcast_api_public_suggest_topics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["podcast_api_public_get_topic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["podcast_api_public_list_people"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["podcast_api_public_get_person"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboards/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["podcast_api_moderation_get_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["podcast_api_search_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest
         * @description Lightweight title/topic completions for a search box.
         */
        get: operations["podcast_api_search_suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["podcast_api_me_get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["podcast_api_me_update_me"];
        trace?: never;
    };
    "/api/episodes/{youtube_id}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Viewer State
         * @description Everything the signed-in user has done with this episode, in one call.
         */
        get: operations["podcast_api_me_get_viewer_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Rating
         * @description Create or update this user's rating. Rating twice updates, never duplicates.
         */
        put: operations["podcast_api_me_set_rating"];
        post?: never;
        /** Clear Rating */
        delete: operations["podcast_api_me_clear_rating"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watch History */
        get: operations["podcast_api_me_get_watch_history"];
        put?: never;
        /**
         * Log Watch
         * @description Append a watch event. A LOG, not a flag - rewatches are the point.
         */
        post: operations["podcast_api_me_log_watch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watch Event */
        delete: operations["podcast_api_me_delete_watch_event"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add Favorite */
        put: operations["podcast_api_me_add_favorite"];
        post?: never;
        /** Remove Favorite */
        delete: operations["podcast_api_me_remove_favorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["podcast_api_me_list_favorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/watched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watched */
        get: operations["podcast_api_me_list_watched"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rated */
        get: operations["podcast_api_me_list_rated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Personal Tag
         * @description 🔒 Private to this user. Never surfaced on any public endpoint.
         */
        post: operations["podcast_api_me_add_personal_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Personal Tag */
        delete: operations["podcast_api_me_delete_personal_tag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Tags */
        get: operations["podcast_api_me_list_my_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Memberships */
        get: operations["podcast_api_me_list_my_memberships"];
        put?: never;
        /**
         * Claim Membership
         * @description Claim membership of a channel. Unverified until an admin reviews it.
         */
        post: operations["podcast_api_me_claim_membership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/memberships/{membership_id}/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Verification Screenshot
         * @description 🔒 Upload proof of membership.
         *
         *     The image is PRIVATE: only admins see it, and only via the admin. It is never
         *     returned by any API endpoint - `has_screenshot` is the only thing exposed.
         */
        post: operations["podcast_api_me_upload_verification_screenshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/memberships/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Membership */
        delete: operations["podcast_api_me_delete_membership"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Comments
         * @description Public read. Hidden comments are never returned.
         */
        get: operations["podcast_api_community_list_comments"];
        put?: never;
        /** Create Comment */
        post: operations["podcast_api_community_create_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Comment */
        delete: operations["podcast_api_community_delete_comment"];
        options?: never;
        head?: never;
        /** Edit Comment */
        patch: operations["podcast_api_community_edit_comment"];
        trace?: never;
    };
    "/api/episodes/{youtube_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Topic
         * @description Attach a topic. Free text resolves to a CANONICAL Topic by unicode slug, so
         *     'Политика' and 'политика' land on the same row.
         */
        post: operations["podcast_api_community_add_topic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episode-topics/{episode_topic_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vote Topic */
        post: operations["podcast_api_community_vote_topic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episode-topics/{episode_topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Topic */
        delete: operations["podcast_api_community_remove_topic"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{youtube_id}/moments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Moments
         * @description Public read. With no creator chapters on these channels, this IS the
         *     in-episode structure.
         */
        get: operations["podcast_api_community_list_moments"];
        put?: never;
        /**
         * Add Moment
         * @description A community timestamp. With no creator chapters on these channels, moments
         *     are the PRIMARY searchable structure inside an episode.
         */
        post: operations["podcast_api_community_add_moment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moments/{moment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Moment */
        delete: operations["podcast_api_community_delete_moment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description 🔒 Moderators only.
         */
        get: operations["podcast_api_moderation_list_reports"];
        put?: never;
        /** Create Report */
        post: operations["podcast_api_moderation_create_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Report
         * @description 🔒 Moderators only.
         */
        post: operations["podcast_api_moderation_resolve_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraw Report */
        delete: operations["podcast_api_moderation_withdraw_report"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DependencyStatus */
        DependencyStatus: {
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            database: components["schemas"]["DependencyStatus"];
            redis: components["schemas"]["DependencyStatus"];
        };
        /** ChannelOut */
        ChannelOut: {
            /** Id */
            id: number;
            /** Youtube Channel Id */
            youtube_channel_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Handle */
            handle: string;
            /** Description */
            description: string;
            /** Avatar Url */
            avatar_url: string;
            /** Banner Url */
            banner_url: string;
            /** Subscriber Count */
            subscriber_count: number | null;
            /**
             * Episode Count
             * @default 0
             */
            episode_count: number;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /** ChannelGridOut */
        ChannelGridOut: {
            /** Channel Name */
            channel_name: string;
            /** Channel Slug */
            channel_slug: string;
            /** Score Kind */
            score_kind: string;
            /** Seasons */
            seasons: components["schemas"]["GridSeasonOut"][];
            /** Rows */
            rows: components["schemas"]["GridRowOut"][];
            /** Overall Average */
            overall_average: number | null;
            /** Rated Count */
            rated_count: number;
            /** Total Count */
            total_count: number;
            /** Bands */
            bands: components["schemas"]["GridBandOut"][];
        };
        /** GridBandOut */
        GridBandOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Min Score */
            min_score: number;
        };
        /**
         * GridCellOut
         * @description One episode inside the heatmap.
         *
         *     🚨 Keep this LEAN. Every field is multiplied by the channel's episode count,
         *     and the biggest channel is already 1,318 episodes. Fields that only a hover
         *     card or a detail view needs (`slug`, `upload_date`, `duration_sec`,
         *     `thumbnail_url`) were removed on 2026-08-09: they were 47% of the payload and
         *     no consumer read them. `thumbnail_url` is derivable from `youtube_id`
         *     anyway - the project rule is to store the video id and build the CDN URL at
         *     render time. Anything richer comes from /api/episodes/{youtube_id}.
         */
        GridCellOut: {
            /** Youtube Id */
            youtube_id: string;
            /** Title */
            title: string;
            /** Content Kind */
            content_kind: string;
            /** Members Only */
            members_only: boolean;
            /** Score */
            score: number | null;
            /** Rating Count */
            rating_count: number;
            /** Band */
            band: string | null;
            /**
             * Is Provisional
             * @default false
             */
            is_provisional: boolean;
        };
        /** GridRowOut */
        GridRowOut: {
            /** Index */
            index: number;
            /** Cells */
            cells: (components["schemas"]["GridCellOut"] | null)[];
        };
        /** GridSeasonOut */
        GridSeasonOut: {
            /** Year */
            year: number;
            /** Label */
            label: string;
            /** Episode Count */
            episode_count: number;
            /** Rated Count */
            rated_count: number;
            /** Average */
            average: number | null;
        };
        /**
         * EpisodeBriefOut
         * @description Card-sized shape for lists. Deliberately excludes description.
         */
        EpisodeBriefOut: {
            /** Id */
            id: number;
            /** Youtube Id */
            youtube_id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Channel Id */
            channel_id: number;
            /** Channel Name */
            channel_name: string;
            /** Channel Slug */
            channel_slug: string;
            /** Upload Date */
            upload_date: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Content Kind */
            content_kind: string;
            /** Members Only */
            members_only: boolean;
            /** Public Score */
            public_score: number | null;
            /** Elite Score */
            elite_score: number | null;
            /** Rating Count */
            rating_count: number;
            /** Elite Rating Count */
            elite_rating_count: number;
            /** Band */
            band?: string | null;
            /** Elite Band */
            elite_band?: string | null;
        };
        /** EpisodeListOut */
        EpisodeListOut: {
            /** Items */
            items: components["schemas"]["EpisodeBriefOut"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /** PaginatedMeta */
        PaginatedMeta: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** ChapterOut */
        ChapterOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Start Sec */
            start_sec: number;
            /** End Sec */
            end_sec: number | null;
        };
        /**
         * EpisodeOut
         * @description Full detail shape.
         */
        EpisodeOut: {
            /** Id */
            id: number;
            /** Youtube Id */
            youtube_id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Channel Id */
            channel_id: number;
            /** Channel Name */
            channel_name: string;
            /** Channel Slug */
            channel_slug: string;
            /** Upload Date */
            upload_date: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Content Kind */
            content_kind: string;
            /** Members Only */
            members_only: boolean;
            /** Public Score */
            public_score: number | null;
            /** Elite Score */
            elite_score: number | null;
            /** Rating Count */
            rating_count: number;
            /** Elite Rating Count */
            elite_rating_count: number;
            /** Band */
            band?: string | null;
            /** Elite Band */
            elite_band?: string | null;
            /** Description */
            description: string;
            /** Url */
            url: string;
            /** Watch Url */
            watch_url: string;
            /** Availability */
            availability: string;
            /** Language */
            language: string;
            /** View Count */
            view_count: number | null;
            /** Like Count */
            like_count: number | null;
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["TopicBriefOut"][];
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterOut"][];
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["PersonBriefOut"][];
            /**
             * Moment Count
             * @default 0
             */
            moment_count: number;
            /**
             * Comment Count
             * @default 0
             */
            comment_count: number;
        };
        /** PersonBriefOut */
        PersonBriefOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Avatar Url */
            avatar_url: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** TopicBriefOut */
        TopicBriefOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** TopicOut */
        TopicOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Episode Count
             * @default 0
             */
            episode_count: number;
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Bio */
            bio: string;
            /** Avatar Url */
            avatar_url: string;
            /**
             * Socials
             * @default {}
             */
            socials: {
                [key: string]: unknown;
            };
            /**
             * Appearance Count
             * @default 0
             */
            appearance_count: number;
        };
        /** PersonDetailOut */
        PersonDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Bio */
            bio: string;
            /** Avatar Url */
            avatar_url: string;
            /**
             * Socials
             * @default {}
             */
            socials: {
                [key: string]: unknown;
            };
            /**
             * Appearance Count
             * @default 0
             */
            appearance_count: number;
            /**
             * Episodes
             * @default []
             */
            episodes: components["schemas"]["EpisodeBriefOut"][];
        };
        /** LeaderboardEntryOut */
        LeaderboardEntryOut: {
            episode: components["schemas"]["EpisodeBriefOut"];
            /** Value */
            value: number | null;
            /** Rank */
            rank: number;
        };
        /** LeaderboardOut */
        LeaderboardOut: {
            /** Kind */
            kind: string;
            /** Items */
            items: components["schemas"]["LeaderboardEntryOut"][];
        };
        /** SearchHitOut */
        SearchHitOut: {
            episode: components["schemas"]["EpisodeBriefOut"];
            /**
             * Matched Topics
             * @default []
             */
            matched_topics: string[];
            /**
             * Matched Moments
             * @default []
             */
            matched_moments: string[];
        };
        /** SearchOut */
        SearchOut: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Backend
             * @description meilisearch | postgres
             */
            backend: string;
            /** Processing Ms */
            processing_ms?: number | null;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string;
            /** Bio */
            bio: string;
            /** Role */
            role: string;
            /**
             * Memberships
             * @default []
             */
            memberships: components["schemas"]["MembershipOut"][];
            /**
             * Rating Count
             * @default 0
             */
            rating_count: number;
            /**
             * Watched Count
             * @default 0
             */
            watched_count: number;
            /**
             * Favorite Count
             * @default 0
             */
            favorite_count: number;
        };
        /** MembershipOut */
        MembershipOut: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Channel Name */
            channel_name: string;
            /** Channel Slug */
            channel_slug: string;
            /** Tier */
            tier: string;
            /** Member Since */
            member_since: string | null;
            /** Is Verified */
            is_verified: boolean;
            /**
             * Has Screenshot
             * @default false
             */
            has_screenshot: boolean;
            /** Verified At */
            verified_at: string | null;
        };
        /** ProfileIn */
        ProfileIn: {
            /** Display Name */
            display_name?: string | null;
            /** Bio */
            bio?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /**
         * ViewerStateOut
         * @description The signed-in user's own relationship to an episode.
         */
        ViewerStateOut: {
            /** Rating */
            rating?: number | null;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
            /**
             * Watch Count
             * @default 0
             */
            watch_count: number;
            /** Last Watched On */
            last_watched_on?: string | null;
            /**
             * Personal Tags
             * @default []
             */
            personal_tags: string[];
        };
        /** RatingOut */
        RatingOut: {
            /** Score */
            score: number;
            /** Episode Id */
            episode_id: number;
            /** Public Score */
            public_score: number | null;
            /** Elite Score */
            elite_score: number | null;
            /** Rating Count */
            rating_count: number;
            /** Elite Rating Count */
            elite_rating_count: number;
        };
        /** RatingIn */
        RatingIn: {
            /** Score */
            score: number;
        };
        /** WatchEventOut */
        WatchEventOut: {
            /** Id */
            id: number;
            /** Episode Id */
            episode_id: number;
            /**
             * Watched On
             * Format: date
             */
            watched_on: string;
            /** Note */
            note: string;
        };
        /** WatchSummaryOut */
        WatchSummaryOut: {
            /** Episode Id */
            episode_id: number;
            /** Watch Count */
            watch_count: number;
            /** Last Watched On */
            last_watched_on: string | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["WatchEventOut"][];
        };
        /** WatchIn */
        WatchIn: {
            /** Watched On */
            watched_on?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Detail */
            detail: string;
        };
        /** FavoriteOut */
        FavoriteOut: {
            /** Episode Id */
            episode_id: number;
            /** Is Favorite */
            is_favorite: boolean;
        };
        /**
         * PersonalTagOut
         * @description 🔒 Private to the owning user. Never returned on a public endpoint.
         */
        PersonalTagOut: {
            /** Id */
            id: number;
            /** Episode Id */
            episode_id: number;
            /** Text */
            text: string;
        };
        /** PersonalTagIn */
        PersonalTagIn: {
            /** Text */
            text: string;
        };
        /** MembershipIn */
        MembershipIn: {
            /** Channel Id */
            channel_id: number;
            /**
             * Tier
             * @default
             */
            tier: string;
            /** Member Since */
            member_since?: string | null;
        };
        /** CommentListOut */
        CommentListOut: {
            /** Items */
            items: components["schemas"]["CommentOut"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /** CommentOut */
        CommentOut: {
            /** Id */
            id: number;
            /** Episode Id */
            episode_id: number;
            /** Body */
            body: string;
            /** Is Spoiler */
            is_spoiler: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Edited At */
            edited_at: string | null;
            /** Author Id */
            author_id: number;
            /** Author Name */
            author_name: string;
            /** Author Avatar */
            author_avatar: string;
        };
        /** CommentIn */
        CommentIn: {
            /** Body */
            body: string;
            /**
             * Is Spoiler
             * @default false
             */
            is_spoiler: boolean;
        };
        /** EpisodeTopicOut */
        EpisodeTopicOut: {
            /** Id */
            id: number;
            topic: components["schemas"]["TopicOut"];
            /** Score */
            score: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** My Vote */
            my_vote?: number | null;
        };
        /** TopicIn */
        TopicIn: {
            /** Name */
            name: string;
        };
        /** VoteIn */
        VoteIn: {
            /** Value */
            value: number;
        };
        /** MomentOut */
        MomentOut: {
            /** Id */
            id: number;
            /** Timestamp Sec */
            timestamp_sec: number;
            /** Label */
            label: string;
            /** Score */
            score: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Author */
            author?: string | null;
        };
        /** MomentIn */
        MomentIn: {
            /** Timestamp Sec */
            timestamp_sec: number;
            /** Label */
            label: string;
        };
        /** ReportOut */
        ReportOut: {
            /** Id */
            id: number;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: number;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Resolution Note
             * @default
             */
            resolution_note: string;
        };
        /** ReportIn */
        ReportIn: {
            /**
             * Target Type
             * @description comment | moment | episodetopic | rating
             */
            target_type: string;
            /** Target Id */
            target_id: number;
            /** Reason */
            reason: string;
        };
        /** ReportResolveIn */
        ReportResolveIn: {
            /**
             * Status
             * @description resolved | dismissed
             */
            status: string;
            /**
             * Resolution Note
             * @default
             */
            resolution_note: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    podcast_api_public_list_channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"][];
                };
            };
        };
    };
    podcast_api_public_get_channel_grid: {
        parameters: {
            query?: {
                /** @description public | elite */
                score?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelGridOut"];
                };
            };
        };
    };
    podcast_api_public_get_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
        };
    };
    podcast_api_public_list_episodes: {
        parameters: {
            query?: {
                /** @description Channel slug */
                channel?: string | null;
                /** @description Topic slug */
                topic?: string | null;
                /** @description Person slug */
                person?: string | null;
                /** @description video | stream */
                kind?: string | null;
                members_only?: boolean | null;
                /** @description Simple title/description contains */
                q?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeListOut"];
                };
            };
        };
    };
    podcast_api_public_get_episode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeOut"];
                };
            };
        };
    };
    podcast_api_public_list_topics: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicOut"][];
                };
            };
        };
    };
    podcast_api_public_suggest_topics: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicOut"][];
                };
            };
        };
    };
    podcast_api_public_get_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicOut"];
                };
            };
        };
    };
    podcast_api_public_list_people: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
        };
    };
    podcast_api_public_get_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
        };
    };
    podcast_api_moderation_get_leaderboard: {
        parameters: {
            query?: {
                /** @description Channel slug */
                channel?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
        };
    };
    podcast_api_search_search: {
        parameters: {
            query?: {
                /** @description Query text. Bulgarian and typos are expected. */
                q?: string;
                /** @description Channel slug */
                channel?: string | null;
                /** @description video | stream */
                kind?: string | null;
                members_only?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
        };
    };
    podcast_api_search_suggest: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    podcast_api_me_get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    podcast_api_me_update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    podcast_api_me_get_viewer_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerStateOut"];
                };
            };
        };
    };
    podcast_api_me_set_rating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingOut"];
                };
            };
        };
    };
    podcast_api_me_clear_rating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingOut"];
                };
            };
        };
    };
    podcast_api_me_get_watch_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchSummaryOut"];
                };
            };
        };
    };
    podcast_api_me_log_watch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WatchIn"] | null;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchSummaryOut"];
                };
            };
        };
    };
    podcast_api_me_delete_watch_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    podcast_api_me_add_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteOut"];
                };
            };
        };
    };
    podcast_api_me_remove_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteOut"];
                };
            };
        };
    };
    podcast_api_me_list_favorites: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeListOut"];
                };
            };
        };
    };
    podcast_api_me_list_watched: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeListOut"];
                };
            };
        };
    };
    podcast_api_me_list_rated: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeListOut"];
                };
            };
        };
    };
    podcast_api_me_add_personal_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalTagIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalTagOut"];
                };
            };
        };
    };
    podcast_api_me_delete_personal_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    podcast_api_me_list_my_tags: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalTagOut"][];
                };
            };
        };
    };
    podcast_api_me_list_my_memberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"][];
                };
            };
        };
    };
    podcast_api_me_claim_membership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"];
                };
            };
        };
    };
    podcast_api_me_upload_verification_screenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"];
                };
            };
        };
    };
    podcast_api_me_delete_membership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    podcast_api_community_list_comments: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListOut"];
                };
            };
        };
    };
    podcast_api_community_create_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
        };
    };
    podcast_api_community_delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    podcast_api_community_edit_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
        };
    };
    podcast_api_community_add_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeTopicOut"];
                };
            };
        };
    };
    podcast_api_community_vote_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_topic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeTopicOut"];
                };
            };
        };
    };
    podcast_api_community_remove_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    podcast_api_community_list_moments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomentOut"][];
                };
            };
        };
    };
    podcast_api_community_add_moment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                youtube_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MomentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomentOut"];
                };
            };
        };
    };
    podcast_api_community_delete_moment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    podcast_api_moderation_list_reports: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"][];
                };
            };
        };
    };
    podcast_api_moderation_create_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
        };
    };
    podcast_api_moderation_resolve_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportResolveIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
        };
    };
    podcast_api_moderation_withdraw_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
}
