# Generated by Django 5.2.17 on 2026-08-08 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_channel_id', models.CharField(max_length=64, unique=True)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('subscriber_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to exclude from scheduled syncs.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('content_kind', models.CharField(choices=[('video', 'Video'), ('stream', 'Live stream')], db_index=True, default='video', max_length=16)),
                ('availability', models.CharField(choices=[('public', 'Public'), ('subscriber_only', 'Members only'), ('unlisted', 'Unlisted')], default='public', max_length=32)),
                ('members_only', models.BooleanField(db_index=True, default=False, help_text='Denormalized from availability so the UI can badge and filter cheaply.')),
                ('language', models.CharField(blank=True, max_length=8)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('like_count', models.BigIntegerField(blank=True, null=True)),
                ('yt_comment_count', models.BigIntegerField(blank=True, null=True)),
                ('public_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('elite_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('elite_rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcast.channel')),
            ],
            options={
                'ordering': ['-upload_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_spoiler', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by a moderator. Kept for audit, not shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='podcast.episode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_sec', models.PositiveIntegerField()),
                ('end_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='podcast.episode')),
            ],
            options={
                'ordering': ['start_sec'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='podcast.episode')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcast.topic')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeTopicVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='podcast.episodetopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='podcast.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_sec', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='podcast.episode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp_sec'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host'), ('guest', 'Guest'), ('producer', 'Producer')], default='guest', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='podcast.episode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='podcast.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tags', to='podcast.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='podcast.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=280)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=280)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='podcast.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.DateField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_screenshot', models.ImageField(blank=True, null=True, upload_to='verifications/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='podcast.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'is_verified'], name='podcast_cha_channel_59d972_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='uniq_membership_per_channel')],
            },
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['channel', '-upload_date'], name='podcast_epi_channel_bf8d86_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['-upload_date'], name='podcast_epi_upload__7a4f38_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['-public_score'], name='podcast_epi_public__6b2d91_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['content_kind', '-upload_date'], name='podcast_epi_content_967504_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('channel', 'slug'), name='uniq_episode_slug_per_channel'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['episode', '-created_at'], name='podcast_com_episode_9ba587_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('episode', 'start_sec'), name='uniq_chapter_start_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='episodetopicvote',
            constraint=models.UniqueConstraint(fields=('episode_topic', 'user'), name='uniq_topic_vote'),
        ),
        migrations.AddConstraint(
            model_name='episodetopicvote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='topic_vote_is_plus_or_minus_one'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'episode'), name='uniq_favorite'),
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['episode', 'timestamp_sec'], name='podcast_mom_episode_28c167_idx'),
        ),
        migrations.AddIndex(
            model_name='episodeparticipant',
            index=models.Index(fields=['person', 'role'], name='podcast_epi_person__7dfd1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='episodeparticipant',
            constraint=models.UniqueConstraint(fields=('episode', 'person'), name='uniq_participant_per_episode'),
        ),
        migrations.AddIndex(
            model_name='personaltag',
            index=models.Index(fields=['user', 'text'], name='podcast_per_user_id_930780_idx'),
        ),
        migrations.AddConstraint(
            model_name='personaltag',
            constraint=models.UniqueConstraint(fields=('user', 'episode', 'text'), name='uniq_personal_tag'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['episode', 'score'], name='podcast_rat_episode_0a6a24_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'episode'), name='uniq_rating_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 10)), name='rating_score_between_1_and_10'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='podcast_rep_status_5b1734_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='podcast_rep_content_60d8df_idx'),
        ),
        migrations.AddIndex(
            model_name='episodetopic',
            index=models.Index(fields=['topic', '-score'], name='podcast_epi_topic_i_d2b4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='episodetopic',
            index=models.Index(fields=['episode', '-score'], name='podcast_epi_episode_712d1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='episodetopic',
            constraint=models.UniqueConstraint(fields=('episode', 'topic'), name='uniq_topic_per_episode'),
        ),
        migrations.AddIndex(
            model_name='watchevent',
            index=models.Index(fields=['user', 'episode'], name='podcast_wat_user_id_d66c61_idx'),
        ),
        migrations.AddIndex(
            model_name='watchevent',
            index=models.Index(fields=['user', '-watched_on'], name='podcast_wat_user_id_8f3a9e_idx'),
        ),
    ]
