# Generated by Django 5.2.17 on 2026-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.OrderBy(models.F('upload_date'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='ep_upload_desc_nl_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.OrderBy(models.F('public_score'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='ep_public_desc_nl_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.OrderBy(models.F('elite_score'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='ep_elite_desc_nl_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.OrderBy(models.F('rating_count'), descending=True), models.OrderBy(models.F('id'), descending=True), name='ep_rating_count_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.F('channel_id'), models.OrderBy(models.F('upload_date'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='ep_ch_upload_desc_nl_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.F('channel_id'), models.OrderBy(models.F('public_score'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='ep_ch_public_desc_nl_idx'),
        ),
    ]
