# Generated by Django 5.2.17 on 2026-08-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_episode_ep_upload_desc_nl_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.OrderBy(models.F('duration_sec'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='ep_duration_desc_nl_idx'),
        ),
    ]
