# Generated by Django 5.2.17 on 2026-08-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_episode_ep_duration_desc_nl_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Transcript stored'), ('unavailable', 'No captions published')], db_index=True, default='ok', max_length=16)),
                ('source', models.CharField(blank=True, choices=[('youtube_auto', 'YouTube auto-captions'), ('youtube_manual', 'Creator-uploaded captions'), ('whisper', 'Whisper'), ('scribe', 'ElevenLabs Scribe')], max_length=32)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('track_id', models.CharField(blank=True, help_text='YouTube caption track, e.g. "bg-orig".', max_length=32)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('covered_sec', models.PositiveIntegerField(default=0, help_text='End of the last segment. Compare with Episode.duration_sec.')),
                ('checked_at', models.DateTimeField(blank=True, help_text='Last COMPLETE fetch attempt. Never set from a throttled one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='podcast.episode')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sec', models.PositiveIntegerField()),
                ('end_sec', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='podcast.transcript')),
            ],
            options={
                'ordering': ['start_sec'],
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['status', 'checked_at'], name='podcast_tra_status_79621e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('transcript', 'start_sec'), name='uniq_segment_start_per_transcript'),
        ),
    ]
