# Generated by Django 5.2.17 on 2026-08-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_transcript_transcriptsegment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='channel',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Lower sorts first. Set by `manage.py set_channel_order`.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, db_index=True, help_text="The user's YouTube handle, e.g. @someone. Assigned by us.", max_length=100, null=True, unique=True),
        ),
    ]
