# Generated by Django 5.2.17 on 2026-08-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_channel_options_channel_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, db_index=True, help_text='Self-chosen public nickname, e.g. @someone. Not verified.', max_length=30, null=True, unique=True),
        ),
    ]
