# Generated by Django 5.2.17 on 2026-08-16 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_userprofile_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmembership',
            name='renewal_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of the month the membership renews (1-31).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_key',
            field=models.CharField(blank=True, help_text='Key into the avatar-icon catalogue. Not a URL.', max_length=64),
        ),
    ]
