# Generated by Django 5.2.17 on 2026-08-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('podcast', '0007_channelmembership_renewal_day_userprofile_avatar_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('wrong_participants', 'Wrong participants'), ('wrong_info', 'Wrong information'), ('not_an_episode', 'Not an episode'), ('bug', 'Something is broken'), ('suggestion', 'Suggestion'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParticipantProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(blank=True, help_text='Free text typed by the member when no persona matched.', max_length=200)),
                ('role', models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host'), ('guest', 'Guest'), ('producer', 'Producer')], default='guest', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Why it was rejected, or which persona a typed name was mapped to.', max_length=280)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_proposals', to='podcast.episode')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='podcast.person')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_proposals', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='podcast_par_status_769b0e_idx'), models.Index(fields=['episode', 'status'], name='podcast_par_episode_1e55c0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('person__isnull', True), ('proposed_name', ''), _negated=True), name='proposal_names_someone'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('episode', 'person', 'proposed_by'), name='uniq_pending_proposal_per_user')],
            },
        ),
    ]
