# Generated by Django 5.2.17 on 2026-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_report_category_alter_report_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host'), ('regular', 'Regular'), ('guest', 'Guest'), ('offcamera', 'Off-camera'), ('producer', 'Producer')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='timestamp_sec',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantproposal',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host'), ('regular', 'Regular'), ('guest', 'Guest'), ('offcamera', 'Off-camera'), ('producer', 'Producer')], default='guest', max_length=20),
        ),
    ]
