# Generated by Django 5.2.17 on 2026-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_alter_episodeparticipant_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name_is_custom',
            field=models.BooleanField(default=False, help_text='The member typed this name themselves; never overwrite it from Clerk.'),
        ),
        migrations.AlterField(
            model_name='episodeparticipant',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('guest', 'Guest'), ('offcamera', 'Off-camera')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='participantproposal',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('guest', 'Guest'), ('offcamera', 'Off-camera')], default='regular', max_length=20),
        ),
    ]
