# Generated by Django 5.2.17 on 2026-08-16 16:09
#
# ⚠️ Scaffolded with `makemigrations --empty` and then filled in, because
# `makemigrations` cannot author a DATA migration - the schema half of this
# change is 0010, which was generated normally. Nothing here is hand-written
# schema.
#
# 🚨 WHY THIS EXISTS AT ALL: Django does not enforce `choices` at the database
# level. Dropping `host`, `cohost` and `producer` from EpisodeParticipant.Role
# in 0010 therefore leaves any existing row holding those strings perfectly
# intact - and the web maps an unrecognised key through `copy.episode.role()`'s
# `?? guest` fallback, so a former host would silently render as a GUEST. That
# is a wrong answer rather than a missing one, which is the failure this
# project keeps paying for elsewhere. Remap instead of hoping the table is
# empty.

from django.db import migrations

# host/cohost -> regular: both described someone who is on the show every week,
#   which is exactly what `regular` now means. The hierarchy between them is the
#   part the owner discarded.
# producer -> offcamera: `producer` was a credit, not a presence in the episode.
#   The nearest surviving concept is the one the owner asked for in the same
#   breath - "the voice behind the camera". This is the only judgement call in
#   the file; if it is wrong it is wrong for a handful of rows and one edit
#   fixes it.
REMAP = {
    "host": "regular",
    "cohost": "regular",
    "producer": "offcamera",
}


def remap(apps, schema_editor):
    for model_name in ("EpisodeParticipant", "ParticipantProposal"):
        model = apps.get_model("podcast", model_name)
        for old, new in REMAP.items():
            model.objects.filter(role=old).update(role=new)


def unremap(apps, schema_editor):
    """Deliberately a no-op.

    The mapping is lossy - `regular` cannot be split back into host and cohost -
    so an "undo" would have to invent which row was which. Reversing to a state
    that never existed is worse than reversing to nothing.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_userprofile_display_name_is_custom_and_more'),
    ]

    operations = [
        migrations.RunPython(remap, unremap),
    ]
